#!/usr/bin/env tsx
/**
 * Converts the CereWorker logo PNG to ANSI half-block character art.
 * Run: pnpm --filter @cereworker/cli generate:logo
 * Output: src/components/logo-data.ts
 */
import sharp from 'sharp';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const INPUT = resolve('/home/vincent/Share/CereWorker logo_small.png');
const OUTPUT = resolve(__dirname, '../src/components/logo-data.ts');
const TARGET_WIDTH = 48;
const ALPHA_THRESHOLD = 64;

function fg(r: number, g: number, b: number): string {
  return `\x1b[38;2;${r};${g};${b}m`;
}

function bg(r: number, g: number, b: number): string {
  return `\x1b[48;2;${r};${g};${b}m`;
}

const RESET = '\x1b[0m';
const UPPER_HALF = '\u2580';
const LOWER_HALF = '\u2584';

interface Pixel {
  r: number;
  g: number;
  b: number;
  a: number;
}

function getPixel(buf: Buffer, width: number, x: number, y: number): Pixel {
  const idx = (y * width + x) * 4;
  return { r: buf[idx], g: buf[idx + 1], b: buf[idx + 2], a: buf[idx + 3] };
}

function isTransparent(p: Pixel): boolean {
  return p.a < ALPHA_THRESHOLD;
}

async function main() {
  const image = sharp(INPUT);
  const meta = await image.metadata();
  if (!meta.width || !meta.height) throw new Error('Cannot read image dimensions');

  const targetHeight = Math.round(meta.height * (TARGET_WIDTH / meta.width));
  // Ensure even height for half-block pairing
  const height = targetHeight % 2 === 0 ? targetHeight : targetHeight + 1;

  const { data, info } = await image
    .resize(TARGET_WIDTH, height, { kernel: 'nearest' })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const buf = Buffer.from(data);
  const lines: string[] = [];

  for (let y = 0; y < info.height; y += 2) {
    let line = '';
    for (let x = 0; x < info.width; x++) {
      const top = getPixel(buf, info.width, x, y);
      const bot = y + 1 < info.height ? getPixel(buf, info.width, x, y + 1) : { r: 0, g: 0, b: 0, a: 0 };
      const topT = isTransparent(top);
      const botT = isTransparent(bot);

      if (topT && botT) {
        line += RESET + ' ';
      } else if (topT) {
        line += fg(bot.r, bot.g, bot.b) + LOWER_HALF;
      } else if (botT) {
        line += fg(top.r, top.g, top.b) + UPPER_HALF;
      } else {
        line += fg(top.r, top.g, top.b) + bg(bot.r, bot.g, bot.b) + UPPER_HALF;
      }
    }
    lines.push(line + RESET);
  }

  const art = lines.join('\n');

  const src = `// Auto-generated by scripts/generate-logo.ts — do not edit manually
export const LOGO_ART = ${JSON.stringify(art)};

export const LOGO_WIDTH = ${TARGET_WIDTH};
`;

  writeFileSync(OUTPUT, src, 'utf-8');
  console.log(`Logo art generated: ${OUTPUT} (${info.width}x${info.height} → ${info.width} cols, ${lines.length} rows)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
